### ISSUE TITLE
html5 in devmode / websocket connection fails, when entering a room

### ISSUE THREAD

**Issue by quark-s** [bigbluebutton/docker-dev#15]
Cheers!

I launched the meteor layer (HTML5) for version 2.6 as described in the readme using ./run-dev.sh.
Everything seems to startup nicely, but after successfully creating a room via API-Mate and joining it as a moderator, the browser console is complaining about not being able to connect to a graphql websocket

`WebSocket connection to 'wss://bbb26.test/v1/graphql' failed:`

Any ideas what's going wrong?

Thx and best regards,
Felix

**Comment by gustavotrott** [comment]
Hey @quark-s,

make sure to checkout the branch `v2.6.x-release`.

The Graphql request was introduces since `v3.0.x-release` or `develop`.

**Comment by quark-s** [comment]
Thank you very much - that fixed it for me indeed!
... added it already in February, but forgot to provide positive feedback 👍
